# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  To modify, adjust your
# /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "iwlmvm" "iwldvm" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/UUID-HERE";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BOOT-UUID-HERE";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # High-level settings
  networking.hostName = "nixos";
}
